### ISSUE TITLE
[KICK] Kick segfault with numerics param

### ISSUE THREAD

**Issue by arthur-trt** [arthur-trt/ft_irc#33]
```
KICK 1 2
```

Segfault occurs, need to find why

**Comment by arthur-trt** [comment]
The problem is not with numeric paramet as this made segfault too :
```
KICK super #test
```

**Comment by arthur-trt** [comment]
```
=================================================================
==624107==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f6a724f6215 bp 0x7ffc0159ff70 sp 0x7ffc0159ed90 T0)
==624107==The signal is caused by a READ memory access.
==624107==Hint: address points to the zero page.
    #0 0x7f6a724f6215 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x143215)
    #1 0x7f6a724f65fd in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x1435fd)
    #2 0x5351fd in cmd_kick(IRC*, User*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /mnt/nfs/homes/atrouill/Documents/ft_irc/srcs/commands/cmd_kick.cpp:57:11
    #3 0x543b4b in cmd_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, IRC*, User*) /mnt/nfs/homes/atrouill/Documents/ft_irc/srcs/commands/cmd_parse.cpp:58:5
    #4 0x4fbe6c in loop(IRC*) /mnt/nfs/homes/atrouill/Documents/ft_irc/srcs/main.cpp:65:5
    #5 0x4fc757 in main /mnt/nfs/homes/atrouill/Documents/ft_irc/srcs/main.cpp:107:2
    #6 0x7f6a720460b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #7 0x422b2d in _start (/mnt/nfs/homes/atrouill/Documents/ft_irc/pIRCarre+0x422b2d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libstdc++.so.6+0x143215) in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
==624107==ABORTING
```
